language: node_js
node_js:
  - "7"
before_script:
  - npm install 
script: 
  - echo "Antes de la construción"
  - npm run build
  -ls
deploy:
  provider: pages
  local-dir: build/
  skip_cleanup: true
  github_token $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
